name: Run e2e tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests on Chrome (headless)
        run: npm run test:chrome

      - name: Run tests on Firefox (headless)
        run: npm run test:firefox

      # Store artifacts
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: |
            cypress/screenshots
            cypress/reports
